### ISSUE TITLE
strlen() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by mudrd8mz** [ssemerikov/moodle-filter_vlabembed#3]
On line 188 of the filter.php there is `strlen($link)` but that is not a string. It is the whole array with the regex matches.

**Comment by mudrd8mz** [comment]
Please make sure to have developer debugging on.

**Comment by mudrd8mz** [comment]
Hmm, why do you even try to do this? Is not $link[1] what you are looking for here?

**Comment by ssemerikov** [comment]
Thanks!
