### ISSUE TITLE
Foreign language translations not needed inside ZIP file

### ISSUE THREAD

**Issue by germanvaleroelizondo** [ssemerikov/moodle-filter_vlabembed#4]
Hi,
I recently translated your filter_vlabembed for the Mexican Spanish language pack of Moodle and I noticed that several non-English language translations were  inside the lang folder of the ZIP file.

Nowadays there is no need to include translations of the plugin English strings inside the ZIP file, as almost all Contributed plugins are now automatically imported into AMOS as described in https://lang.moodle.org/mod/forum/discuss.php?d=2485.

I have submitted the de, ru and uk translations that were inside your ZIP file to the language packs maintainers at AMOS in https://lang.moodle.org/.. They should be revised and included in the Moodle language packs shortly.

You can register in AMOS and submit more languages translations for your plugin, or update the existing translations.

Thanks in advance for your help.

**Comment by germanvaleroelizondo** [comment]
As of today, the russian, ukranian and german translations have been accepted by the Moodle language packs maintainers.

The German language pack maintainer had to a lot of corrections for the text strings. That is one of the reasons why it is better to handle all foreign (non-English) string translations for Moodle plugins at AMOS.

I started a highly illustrated step-by-step Moodle Docs page for this plugin at https://docs.moodle.org/29/en/Virtual_lab_filter , so that Moodle Documentation for this plugin can be later easily translated into other languages. I will do the spanish translation for this documentation page shortly, as soon as I get this plugin to work in my local server.. I am currently experiencing problems with Moodle 2.9.1

**Comment by ssemerikov** [comment]
Thanks!
